In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
print(array1)

[1 2 3 4 5]


In [5]:
l1 = [1,2,3,4,5,6]

In [6]:
l1

[1, 2, 3, 4, 5, 6]

In [7]:
print(l1)

[1, 2, 3, 4, 5, 6]


In [8]:
array1

array([1, 2, 3, 4, 5])

In [9]:
type(l1)

list

In [10]:
type(array1)

numpy.ndarray

In [11]:
print(type(l1))

<class 'list'>


In [12]:
print(type(array1))

<class 'numpy.ndarray'>


In [13]:
%timeit [j**4 for j in range(1,11)]

1.02 µs ± 557 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
%timeit np.arange(1,11)**4

5.21 µs ± 194 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
a = np.array([23,34,21,14])

In [16]:
a

array([23, 34, 21, 14])

In [17]:
print(a)

[23 34 21 14]


# Array

In [18]:
l2 = [23,35,56,67,878,76]
a1 = np.array(l2)
print(a1)

[ 23  35  56  67 878  76]


In [19]:
a1

array([ 23,  35,  56,  67, 878,  76])

In [20]:
l1

[1, 2, 3, 4, 5, 6]

In [21]:
l2

[23, 35, 56, 67, 878, 76]

In [22]:
print(type(a1))

<class 'numpy.ndarray'>


In [23]:
ll = []
for i in range(1,5):
    c = input("Enter : ")
    ll.append(c)

print(np.array(ll))

Enter :  12
Enter :  21
Enter :  23
Enter :  34


['12' '21' '23' '34']


In [24]:
ll

['12', '21', '23', '34']

In [25]:
ll1 = []
for i in range(1,11):
    p = int(input("Enter Integers : "))
    ll1.append(p)
print(np.array(ll1))

Enter Integers :  12
Enter Integers :  22
Enter Integers :  23
Enter Integers :  234
Enter Integers :  43
Enter Integers :  23
Enter Integers :  12
Enter Integers :  23
Enter Integers :  321
Enter Integers :  32


[ 12  22  23 234  43  23  12  23 321  32]


In [26]:
ll1

[12, 22, 23, 234, 43, 23, 12, 23, 321, 32]

In [27]:
o = np.array(ll1)

In [28]:
o

array([ 12,  22,  23, 234,  43,  23,  12,  23, 321,  32])

In [29]:
o.ndim

1

In [30]:
print(o.ndim)

1


In [31]:
ar2 = np.array([[1,3,4,5,6],[6,8,7,6,3]])

In [32]:
ar2

array([[1, 3, 4, 5, 6],
       [6, 8, 7, 6, 3]])

In [33]:
print(ar2)

[[1 3 4 5 6]
 [6 8 7 6 3]]


In [34]:
print(ar2.ndim)

2


In [35]:
ar2.ndim

2

In [36]:
ar3 = np.array([[[123,23,34],[234,564,87],[23,434,56]],[[123,432,34],[12,23,3],[21,23,34]]])

In [37]:
ar3

array([[[123,  23,  34],
        [234, 564,  87],
        [ 23, 434,  56]],

       [[123, 432,  34],
        [ 12,  23,   3],
        [ 21,  23,  34]]])

In [38]:
ar3.ndim

3

In [39]:
print(ar3.ndim)

3


In [40]:
arn = np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


# Zero valued Array

# *zeros

In [41]:
zar1 = np.zeros(6)

In [42]:
zar1

array([0., 0., 0., 0., 0., 0.])

In [43]:
print(zar1)

[0. 0. 0. 0. 0. 0.]


In [44]:
zar2 = np.zeros((2,3))

In [45]:
zar2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
zar3 = np.zeros((4,3,2))

In [47]:
zar3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [48]:
zar4 = np.zeros((4,5,3,2))

In [49]:
zar4

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0.

# *ones

In [50]:
a11 = np.ones(3)

In [51]:
a11

array([1., 1., 1.])

In [52]:
print(a11)

[1. 1. 1.]


In [53]:
a12 = np.ones((3,4))

In [54]:
a12

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
print(a12)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
a13 = np.ones((3,2,4))

In [57]:
a13

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [58]:
print(a13)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# *empty

In [59]:
arr1 = np.empty(12)

In [60]:
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [62]:
arr2 = np.empty((4,3,2))

In [63]:
arr2

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [64]:
print(arr2)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


# *arange

In [65]:
arrr3 = np.arange(7)

In [66]:
arrr3

array([0, 1, 2, 3, 4, 5, 6])

In [67]:
print(arrr3)

[0 1 2 3 4 5 6]


In [68]:
arr3 = np.arange((5))

In [69]:
arr3

array([0, 1, 2, 3, 4])

In [70]:
print(arr3)

[0 1 2 3 4]


# *diagonal

In [71]:
arr4 = np.eye(4)

In [72]:
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
arr5 = np.eye(3,5)

In [75]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [76]:
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


 # *linspace

In [77]:
arr6 = np.linspace(1,10,5)

In [78]:
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [79]:
print(arr6)

[ 1.    3.25  5.5   7.75 10.  ]


# Random

# rand()

In [80]:
v1 = np.random.rand(5)

In [81]:
v1

array([0.36849611, 0.02902727, 0.73079655, 0.9271421 , 0.71340994])

In [82]:
print(v1)

[0.36849611 0.02902727 0.73079655 0.9271421  0.71340994]


In [83]:
v2 = np.random.rand(3,4)

In [84]:
print(v2)

[[0.61755916 0.77019767 0.99829699 0.34592131]
 [0.92177238 0.66763143 0.28279784 0.73692693]
 [0.46153021 0.99260934 0.16234517 0.61917415]]


In [85]:
v2

array([[0.61755916, 0.77019767, 0.99829699, 0.34592131],
       [0.92177238, 0.66763143, 0.28279784, 0.73692693],
       [0.46153021, 0.99260934, 0.16234517, 0.61917415]])

In [86]:
v3 = np.random.rand(3,4,5)

In [87]:
v3

array([[[0.51810905, 0.6191585 , 0.18510691, 0.37805616, 0.8139329 ],
        [0.64524343, 0.60017013, 0.37926719, 0.06187874, 0.84860084],
        [0.65999593, 0.5037038 , 0.43003451, 0.23512838, 0.11216653],
        [0.18780874, 0.1730999 , 0.70352033, 0.07569547, 0.39416144]],

       [[0.76721572, 0.3440321 , 0.54930391, 0.95689795, 0.22478748],
        [0.0589765 , 0.89173696, 0.51836495, 0.82266395, 0.14473887],
        [0.91259812, 0.77424122, 0.05456004, 0.84419171, 0.89476826],
        [0.4732553 , 0.42687263, 0.15122776, 0.36436522, 0.48467499]],

       [[0.18891967, 0.763037  , 0.75988907, 0.36097617, 0.94914549],
        [0.89550961, 0.30739402, 0.39211651, 0.97159909, 0.17731902],
        [0.92573262, 0.89258244, 0.74729742, 0.99435815, 0.70046893],
        [0.69353863, 0.49808241, 0.35808931, 0.38312674, 0.63797481]]])

# randn()

In [88]:
vr1 = np.random.randn(5)

In [89]:
vr1

array([ 0.4662133 , -1.00579681,  1.08907578,  0.08530312,  0.96125496])

In [90]:
print(vr1)

[ 0.4662133  -1.00579681  1.08907578  0.08530312  0.96125496]


In [91]:
vr2 = np.random.randn(4,5,3)

In [92]:
print(vr2)

[[[-1.53601478  0.11898505  0.70534461]
  [ 0.16107037  0.36907881  1.14122836]
  [ 0.31063682 -0.5168224  -1.9723331 ]
  [ 0.68041262 -0.98030319  0.08473509]
  [ 0.1864412  -1.47118804 -0.62259178]]

 [[-0.60045918  1.16041566  0.7722839 ]
  [-1.57632856  0.71798653 -1.50009187]
  [ 1.15205988  1.02802996 -1.55453595]
  [-0.33737688  0.81552034  0.40232035]
  [ 0.53806226 -3.03287488 -0.20739138]]

 [[ 0.2580184   0.42977957  1.57334266]
  [ 1.00006993  1.21981403 -0.67314552]
  [ 0.48697866 -1.19622697 -2.03786395]
  [-0.92366823  0.36178084  0.44034151]
  [-0.28525186 -0.24434204 -0.21660644]]

 [[ 1.37778081 -0.48762471 -0.62598043]
  [-0.84388929  1.93592973 -0.01543998]
  [ 1.96863517  1.05848633 -0.45539126]
  [ 1.52030626 -0.61040923  0.80257655]
  [ 2.13166376  1.0081929   0.24952956]]]


# ranf()

In [93]:
vr3 = np.random.ranf(45)

In [94]:
vr3

array([0.26756521, 0.27218659, 0.42963609, 0.0279034 , 0.38899472,
       0.73946931, 0.7701902 , 0.950261  , 0.55600903, 0.46143954,
       0.72467117, 0.91456258, 0.67698589, 0.39359723, 0.44874196,
       0.35964575, 0.24374287, 0.47956776, 0.23206731, 0.60534567,
       0.72073171, 0.65543951, 0.64687671, 0.21357663, 0.00288906,
       0.48629938, 0.50730423, 0.90262995, 0.51661032, 0.98271552,
       0.7165931 , 0.89534636, 0.54210339, 0.33841988, 0.89449165,
       0.1508863 , 0.89567574, 0.64969208, 0.65124683, 0.57110661,
       0.84063797, 0.02165627, 0.78840041, 0.00719325, 0.81672325])

In [95]:
print(vr3)

[0.26756521 0.27218659 0.42963609 0.0279034  0.38899472 0.73946931
 0.7701902  0.950261   0.55600903 0.46143954 0.72467117 0.91456258
 0.67698589 0.39359723 0.44874196 0.35964575 0.24374287 0.47956776
 0.23206731 0.60534567 0.72073171 0.65543951 0.64687671 0.21357663
 0.00288906 0.48629938 0.50730423 0.90262995 0.51661032 0.98271552
 0.7165931  0.89534636 0.54210339 0.33841988 0.89449165 0.1508863
 0.89567574 0.64969208 0.65124683 0.57110661 0.84063797 0.02165627
 0.78840041 0.00719325 0.81672325]


In [96]:
vr4 = np.random.rand(3,4,5)

In [97]:
print(vr4)

[[[0.24216055 0.23258356 0.79782506 0.87564259 0.25846795]
  [0.86713571 0.37542501 0.47866321 0.97085089 0.61164443]
  [0.00816903 0.85805008 0.09977535 0.00953528 0.8981214 ]
  [0.69930656 0.07118339 0.39820963 0.2876505  0.97244396]]

 [[0.9562841  0.92270315 0.64893307 0.5153534  0.65499794]
  [0.69063721 0.82635362 0.30155799 0.1607332  0.63116252]
  [0.89957607 0.42831714 0.9841064  0.11654641 0.53019313]
  [0.32657034 0.66796657 0.98926069 0.05436098 0.43973414]]

 [[0.22770299 0.48044949 0.81841738 0.26390771 0.4457815 ]
  [0.74882335 0.73898471 0.0996164  0.07983176 0.306277  ]
  [0.79795604 0.52783487 0.61981359 0.91795155 0.33758903]
  [0.22766446 0.98161111 0.25990784 0.98802219 0.43831054]]]


# randint()

In [98]:
var1 = np.random.randint(5,35,5)

In [99]:
var1

array([ 7, 24, 31,  9, 27])

In [100]:
print(var1)

[ 7 24 31  9 27]


In [101]:
var2 = np.random.randint(5,55,(2,3,4))

In [102]:
print(var2)

[[[24 10 14 43]
  [ 7 32 24 23]
  [21 14 17 49]]

 [[54 32 22 28]
  [54  6 29 43]
  [23 45 38 36]]]


# Data Types

In [103]:
ar1 = np.array([1,23,34,45,5,551,5])

In [104]:
type(ar1)

numpy.ndarray

In [105]:
print("Data Type : ",ar1.dtype)

Data Type :  int32


In [106]:
v1 = np.array([2.4,3.5,34,34.34])

In [107]:
type(v1)

numpy.ndarray

In [108]:
print(v1.dtype)

float64


In [109]:
p = np.array(["r","m","v","p"])

In [110]:
print(p)
print(p.dtype)

['r' 'm' 'v' 'p']
<U1


In [111]:
p = np.array(["r","m","v","p",1,4,6,6])
print(p)
print(p.dtype)

['r' 'm' 'v' 'p' '1' '4' '6' '6']
<U11


In [112]:
a = np.array([12,2,43,45,56],dtype = float)
print(a)
print(type(a))
print(a.dtype)

[12.  2. 43. 45. 56.]
<class 'numpy.ndarray'>
float64


In [113]:
b = np.array([2,23,4,5], dtype = "f")
print(b.dtype)

float32


In [114]:
b = np.array([2,23,4,5], dtype = "U")
print(b.dtype)

<U2


In [115]:
b = np.array([2,23,4,5], dtype = "b")
print(b.dtype)

int8


In [116]:
b = np.array([2,23,4,5], dtype = "c")
print(b.dtype)

|S1


In [117]:
print(b)

[b'2' b'2' b'4' b'5']


In [118]:
a = np.array([12,2,43,45,56],dtype = np.int_)
print(a)
print(type(a))
print(a.dtype)

[12  2 43 45 56]
<class 'numpy.ndarray'>
int32


In [119]:
a = np.array([12,2,43,45,56],dtype = np.int8)
print(a)
print(type(a))
print(a.dtype)

[12  2 43 45 56]
<class 'numpy.ndarray'>
int8


In [120]:
a = np.array([12,2,43,45,56],dtype = np.bool_)
print(a)
print(type(a))
print(a.dtype)

[ True  True  True  True  True]
<class 'numpy.ndarray'>
bool


In [121]:
a = np.array([12,2,43,45,56],dtype = "U")
print(a)
print(type(a))
print(a.dtype)

['12' '2' '43' '45' '56']
<class 'numpy.ndarray'>
<U2


In [122]:
a = np.array([12,2,43,45,56],dtype = "f")
print(a)
print(type(a))
print(a.dtype)

[12.  2. 43. 45. 56.]
<class 'numpy.ndarray'>
float32


In [127]:
l = np.array([1,2,3,4,5])
print(l)
print(l.dtype)
n = np.float32(l)
print(n)
print(n.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


In [128]:
b = np.bool_(n)
print(b)
print(b.dtype)

[ True  True  True  True  True]
bool


In [129]:
h=b.astype(float)
print(h)
print(h.dtype)

[1. 1. 1. 1. 1.]
float64
