# Shape

In [1]:
import numpy as np

In [2]:
var = np.array([[1,2],[2,3]])

In [3]:
print(var)
print(var.shape)

[[1 2]
 [2 3]]
(2, 2)


In [4]:
v1 = np.array([1,2,3,4,5],ndmin=5)
print(v1)
print(v1.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [5]:
print(v1.ndim)

5


# Reshape

In [6]:
v = np.array([1,2,3,4,5,6])
print(v)
print()
r = v.reshape(2,3)
print(r)

r2 = r.reshape(3,2)
print()
print(r2)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [7]:
a = np.array([1,2,3,4,5,6,7,8,9,11,12,12])
c=a.reshape(3,2,2)
print(a)
print()
print(c)

[ 1  2  3  4  5  6  7  8  9 11 12 12]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 11]
  [12 12]]]


In [8]:
print(c.ndim)

3


In [9]:
a.ndim

1

In [10]:
r = c.reshape(-1)
print(r)
print(r.ndim)

print()
rr = c.reshape(12)
print(rr)
print(rr.ndim)

[ 1  2  3  4  5  6  7  8  9 11 12 12]
1

[ 1  2  3  4  5  6  7  8  9 11 12 12]
1


# Arithmetic Operation

In [11]:
a1 = np.array([1,2,3,4,5])
a2 = a1+3
print(a2)

[4 5 6 7 8]


In [12]:
a1 = [1,23,3,4,5]
a2 = [1,2,3,4,5]
a3 = np.add(a1,a2)
print(a1)

[1, 23, 3, 4, 5]


In [13]:
print(a2)
print(a3)

[1, 2, 3, 4, 5]
[ 2 25  6  8 10]


In [14]:
a4 = np.subtract(a1,a2)
print(a4)

[ 0 21  0  0  0]


In [15]:
reciprocal = np.reciprocal(a1)
print(reciprocal)

[1 0 0 0 0]


In [16]:
a1
a2


[1, 2, 3, 4, 5]

In [17]:
print(a1)
print(a2)

[1, 23, 3, 4, 5]
[1, 2, 3, 4, 5]


In [18]:
aa = np.multiply(a1,a2)
print(aa)

[ 1 46  9 16 25]


In [19]:
aa1 = np.divide(a1,a2)

In [20]:
print(aa1)

[ 1.  11.5  1.   1.   1. ]


In [21]:
aa2 = np.mod(a1,a2)

In [22]:
aa2

array([0, 1, 0, 0, 0])

In [23]:
a4 = np.power(a1,a2)

In [24]:
print(a4)

[   1  529   27  256 3125]


In [25]:
r = np.array([1,0.5,.25,.75])

In [26]:
print(r)


[1.   0.5  0.25 0.75]


In [27]:
rr = np.reciprocal(r)

In [28]:
print(rr)

[1.         2.         4.         1.33333333]


# Arithmetic operations in case of 2D array

In [29]:
l = np.array([[1,2,3],[4,5,6]])

In [30]:
r = np.reciprocal(l)
print(r)

[[1 0 0]
 [0 0 0]]


In [31]:
r=np.add(r,5)
print(r)

[[6 5 5]
 [5 5 5]]


In [32]:
a = np.multiply(l,r)
print(a)
print(a.shape)

[[ 6 10 15]
 [20 25 30]]
(2, 3)


In [33]:
b = a.reshape(3,2)

In [34]:
print(b)

[[ 6 10]
 [15 20]
 [25 30]]


In [35]:
print(b.T)

[[ 6 15 25]
 [10 20 30]]


In [36]:
n = np.subtract(a,b.T)
print(n)

[[  0  -5 -10]
 [ 10   5   0]]


# Arithmetic functions

In [37]:
ar = np.array([1,2,5,3,4,5,1])

print("Min : ",np.min(ar))
print("Max : ",np.max(ar))
print("argmin : ",np.argmin(ar))
print("argmin : ",np.argmax(ar))
print("sqrt : ",np.sqrt(ar))
print("sin : ",np.sin(ar))
print("cos : ",np.cos(ar))
print("cumsum : ",np.cumsum(ar))

Min :  1
Max :  5
argmin :  0
argmin :  2
sqrt :  [1.         1.41421356 2.23606798 1.73205081 2.         2.23606798
 1.        ]
sin :  [ 0.84147098  0.90929743 -0.95892427  0.14112001 -0.7568025  -0.95892427
  0.84147098]
cos :  [ 0.54030231 -0.41614684  0.28366219 -0.9899925  -0.65364362  0.28366219
  0.54030231]
cumsum :  [ 1  3  8 11 15 20 21]


In [38]:
ar = np.array([[1,2,4,3],[3,2,1,5]])
print("Min : ",np.min(ar))
print("Max : ",np.max(ar))
print("argmin : ",np.argmin(ar))
print("argmin : ",np.argmax(ar))
print("sqrt : ",np.sqrt(ar))
print("sin : ",np.sin(ar))
print("cos : ",np.cos(ar))
print("cumsum : ",np.cumsum(ar))

Min :  1
Max :  5
argmin :  0
argmin :  7
sqrt :  [[1.         1.41421356 2.         1.73205081]
 [1.73205081 1.41421356 1.         2.23606798]]
sin :  [[ 0.84147098  0.90929743 -0.7568025   0.14112001]
 [ 0.14112001  0.90929743  0.84147098 -0.95892427]]
cos :  [[ 0.54030231 -0.41614684 -0.65364362 -0.9899925 ]
 [-0.9899925  -0.41614684  0.54030231  0.28366219]]
cumsum :  [ 1  3  7 10 13 15 16 21]


In [39]:
ar

array([[1, 2, 4, 3],
       [3, 2, 1, 5]])

In [40]:
print(np.min(ar,axis=0))
print(np.min(ar,axis=1))

[1 2 1 3]
[1 1]


In [41]:
print(np.max(ar,axis=0))
print(np.max(ar,axis=1))

[3 2 4 5]
[4 5]


In [42]:
print(np.argmin(ar,axis=0))
print(np.argmin(ar,axis=1))

[0 0 1 0]
[0 2]


In [43]:
print(np.argmax(ar,axis=0))
print(np.argmax(ar,axis=1))

[1 0 0 1]
[2 3]


In [44]:
print(ar)

[[1 2 4 3]
 [3 2 1 5]]


# Broadcasting Numpy Arrays

In [45]:
a1 = np.array([5,6,7])
print(a1.shape)

(3,)


In [46]:
a2 = np.array([[1],[2],[3]])
print(a2)
print(a1+a2)

[[1]
 [2]
 [3]]
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [47]:
print((a1+a2).shape)

(3, 3)


In [48]:
print(a2.shape)

(3, 1)


In [49]:
print(a1+a2+2)

[[ 8  9 10]
 [ 9 10 11]
 [10 11 12]]


In [50]:
l1 = np.array([[1],[3]])
l2 = np.array([[1,2,3],[3,4,5]])
print(l1.shape)
print(l2.shape)

(2, 1)
(2, 3)


In [51]:
print(l1+l2)

[[2 3 4]
 [6 7 8]]


In [52]:
print((l1+l2).shape)

(2, 3)


In [53]:
t1 = np.array([23,34])
t2 = np.array([1,2,3])
print(t1.shape)
print(t2.shape)

(2,)
(3,)


In [55]:
print(t1+2)

[25 36]


In [56]:
a = np.array([[4,5,1],[2,1,3]])
b = np.array([12,23,34])
print(a.shape)

(2, 3)


In [57]:
print(b.shape)

(3,)


In [58]:
print(a+b)

[[16 28 35]
 [14 24 37]]


In [59]:
c=np.array([12,23])
print(c.shape)

(2,)


In [61]:
# print(a+c)  this will throw an error